<a href="https://colab.research.google.com/github/kennycaiguo/LearnPytorchWithColab/blob/main/torch_tutorial_lesson1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

mydevice = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
mytensor = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device=mydevice,requires_grad=True) #创建tensor的时候可以指定使用cuda还是普通cpu建议使用cuda

# print(mytensor)
# print(mytensor.dtype)
# print(mytensor.device)
# print(mytensor.shape)
# print(mytensor.requires_grad)

# 可以创建一个空的tensor对象
# empty_tensor = torch.tensor([]) # 创建空对象方法1
# empty_tensor = torch.empty(size=(3,3)) # 创建空对象方法2
# print(empty_tensor.shape)
# print(empty_tensor.size())

# 可以创建全部都是0的tensor对象
# zero_tensor = torch.zeros(3,3)
# print(zero_tensor)
# print(zero_tensor.shape)

# 可以创建全部都是1的tensor对象
# one_tensor = torch.ones(2,5)
# print(one_tensor)
# print(one_tensor.shape)

# 可以创建对角线是1,其他位置是0的tensor对象
# eye_tensor = torch.eye(5,5)
# print(eye_tensor)
# print(eye_tensor.shape)

# 可以用0-1的随机数来创建tensor对象
# rnd_tensor = torch.rand(2,3)
# print(rnd_tensor)
# print(rnd_tensor.shape)

# 还可以使用arange函数来创建
# a_tensor = torch.arange(start=0,end=5,step=1)
# print(a_tensor)
# print(a_tensor.shape)

# 还可以使用linspace函数来创建tensor
# l_tensor = torch.linspace(start=0.1,end=1,steps=10)
# print(l_tensor)
# print(l_tensor.shape)

# tensor转化为其他数据类型
tensor1 = torch.arange(4)
print(tensor1)
print(tensor1.bool()) # 转化为布尔类型
print(tensor1.short()) # 转化为短整型
print(tensor1.int()) # 转化为整型
print(tensor1.long()) # 转化为长整型

print(tensor1.half()) # 转化为半精度浮点型 float16
print(tensor1.float()) # 转化为单精度浮点型 float32
print(tensor1.double()) # 转化为双精度浮点型 float64s

tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3], dtype=torch.int32)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [2]:
# ndarray=>tensor以及tensor->ndarray
import numpy as np
arr = np.zeros((5,5))
#ndarray=>tensor
tensor = torch.from_numpy(arr)
print(tensor)
print(type(tensor))

#tensor->ndarray
arr2 = tensor.numpy()
print(arr2)
print(type(arr2))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
<class 'torch.Tensor'>
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [3]:
# tensor类型的运算
# add
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])
z1 = torch.empty(3)
torch.add(x,y,out=z1)#调用torch的add方法,其实就是两个tensor对象对应的元素相加
print(z1)
z2 = torch.add(x,y)#调用torch的add方法,其实就是两个tensor对象对应的元素相加
print(z2)
z = x+y #直接进行相加,其实就是两个tensor对象对应的元素相加
print(z)


tensor([10., 10., 10.])
tensor([10, 10, 10])
tensor([10, 10, 10])


In [4]:
#subtract
res = x - y
print(res)
res = torch.subtract(x,y)
print(res)


tensor([-8, -6, -4])
tensor([-8, -6, -4])


In [6]:
# division
res = torch.true_divide(x,y)
print(res)
res = x/y
print(res)

tensor([0.1111, 0.2500, 0.4286])
tensor([0.1111, 0.2500, 0.4286])
