<a href="https://colab.research.google.com/github/kennycaiguo/-LearnPytorchWithColab/blob/main/torch_tutorial_lesson1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

mydevice = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
mytensor = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device=mydevice,requires_grad=True) #创建tensor的时候可以指定使用cuda还是普通cpu建议使用cuda

# print(mytensor)
# print(mytensor.dtype)
# print(mytensor.device)
# print(mytensor.shape)
# print(mytensor.requires_grad)

# 可以创建一个空的tensor对象
# empty_tensor = torch.tensor([]) # 创建空对象方法1
# empty_tensor = torch.empty(size=(3,3)) # 创建空对象方法2
# print(empty_tensor.shape)
# print(empty_tensor.size())

# 可以创建全部都是0的tensor对象
# zero_tensor = torch.zeros(3,3)
# print(zero_tensor)
# print(zero_tensor.shape)

# 可以创建全部都是1的tensor对象
# one_tensor = torch.ones(2,5)
# print(one_tensor)
# print(one_tensor.shape)

# 可以创建对角线是1,其他位置是0的tensor对象
# eye_tensor = torch.eye(5,5)
# print(eye_tensor)
# print(eye_tensor.shape)

# 可以用0-1的随机数来创建tensor对象
# rnd_tensor = torch.rand(2,3)
# print(rnd_tensor)
# print(rnd_tensor.shape)

# 还可以使用arange函数来创建
# a_tensor = torch.arange(start=0,end=5,step=1)
# print(a_tensor)
# print(a_tensor.shape)

# 还可以使用linspace函数来创建tensor
# l_tensor = torch.linspace(start=0.1,end=1,steps=10)
# print(l_tensor)
# print(l_tensor.shape)

# tensor转化为其他数据类型
tensor1 = torch.arange(4)
print(tensor1)
print(tensor1.bool()) # 转化为布尔类型
print(tensor1.short()) # 转化为短整型
print(tensor1.int()) # 转化为整型
print(tensor1.long()) # 转化为长整型

print(tensor1.half()) # 转化为半精度浮点型 float16
print(tensor1.float()) # 转化为单精度浮点型 float32
print(tensor1.double()) # 转化为双精度浮点型 float64s

tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3], dtype=torch.int32)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [2]:
# ndarray=>tensor以及tensor->ndarray
import numpy as np
arr = np.zeros((5,5))
#ndarray=>tensor
tensor = torch.from_numpy(arr)
print(tensor)
print(type(tensor))

#tensor->ndarray
arr2 = tensor.numpy()
print(arr2)
print(type(arr2))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
<class 'torch.Tensor'>
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [3]:
# tensor类型的运算
# add
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])
z1 = torch.empty(3)
torch.add(x,y,out=z1)#调用torch的add方法,其实就是两个tensor对象对应的元素相加
print(z1)
z2 = torch.add(x,y)#调用torch的add方法,其实就是两个tensor对象对应的元素相加
print(z2)
z = x+y #直接进行相加,其实就是两个tensor对象对应的元素相加
print(z)


tensor([10., 10., 10.])
tensor([10, 10, 10])
tensor([10, 10, 10])


In [4]:
#subtract
res = x - y
print(res)
res = torch.subtract(x,y)
print(res)


tensor([-8, -6, -4])
tensor([-8, -6, -4])


In [5]:
# division
res = torch.true_divide(x,y)
print(res)
res = x/y
print(res)

tensor([0.1111, 0.2500, 0.4286])
tensor([0.1111, 0.2500, 0.4286])


In [6]:
# 上面的运算都不是原地操作,他们会返回新的tensor
# 下面我们来学习原地操作这些函数都是带_的
# 1.add_()
t = torch.zeros(3)
t.add_(x)
# print(t)
t += x # t = t + x
# print(t)

# 2.subtract_()
t.subtract_(x)
# print(t)
t -= x
# print(t)

# 3.divide_()
t1 = torch.tensor([2,4,6], dtype=torch.float32) # 奇怪,这里如果不把数据类型改为float,会报错
t1.divide_(x)
print(t1)

tensor([2., 2., 2.])


In [7]:
# 指数操作
# 写法1
# cub = x.pow(3)
# print(cub)
# 写法2
cub = x**3
print(cub)


tensor([ 1,  8, 27])


In [8]:
# tensor对象的比较
print(x>0) # tensor([True, True, True]) 一个tensor和一个数字比较,也就是把这个tensor对象里面的所有元素都和这个数字比较,返回值是一个又布尔值组成的tensor
# 两个tensor对象比较,也就是他们对应位置的元素的比较,(这两个tensor的形状必须完全相同)
print(x<y) # tensor([True, True, True])

tensor([True, True, True])
tensor([True, True, True])


In [10]:
#矩阵乘法,要做矩阵乘法,第一个矩阵的列数需要等于第二个矩阵的行数,然后结果的行数是第一个矩阵的行数,结果的列数是第二个矩阵的列数
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm(x1,x2) #矩阵乘法,方法1
print(x3) # 是一个2行3列的tensor(是矩阵来的)tensor([[1.6750, 1.6855, 1.4011],[1.3710, 1.0602, 0.9070]])
x4 = x1.mm(x2) # 矩阵乘法,写法2
print(x4)

tensor([[1.0695, 0.8425, 1.3662],
        [2.0211, 2.2844, 2.2732]])
tensor([[1.0695, 0.8425, 1.3662],
        [2.0211, 2.2844, 2.2732]])


In [12]:
# 矩阵的幂运算
matrix = torch.rand(5,5)
matrix_exp = matrix.matrix_power(3)
print(matrix_exp)
matrix_exp2 = matrix**3 # 这种写法得到的结果和上面不一样!!!
print(matrix_exp2)

tensor([[3.8743, 3.8256, 5.1538, 4.0212, 3.6105],
        [4.6265, 4.5152, 6.1594, 4.7186, 4.4253],
        [6.2076, 6.1248, 8.4498, 6.4324, 5.9229],
        [5.3377, 5.3127, 7.3359, 5.5942, 5.0534],
        [3.5366, 3.4530, 4.7783, 3.6131, 3.4238]])
tensor([[4.8420e-02, 1.1302e-01, 7.1676e-01, 3.9025e-04, 1.2646e-01],
        [9.9979e-02, 4.8740e-03, 3.4420e-01, 2.0070e-01, 9.3489e-01],
        [3.1797e-01, 6.6804e-01, 9.2563e-01, 5.5308e-01, 4.5056e-02],
        [7.0040e-01, 4.1553e-01, 1.3547e-01, 3.6260e-01, 1.8881e-01],
        [2.7754e-02, 3.2511e-02, 2.0154e-01, 1.9822e-01, 2.2404e-02]])


In [13]:
# 两个tensor对应位的元素相乘
res = x * y  #[1*9,2*8,3*7]
print(res)

tensor([ 9, 16, 21])


In [14]:
# tensor矩阵的点乘
dot_res = torch.dot(x,y) # [1*9 + 2*8 + 3*7]
print(dot_res)

tensor(46)


In [16]:
#批量矩阵乘法,torch.bmm()
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch,n,m))
tensor2 = torch.rand((batch,m,p))
out_bmm = torch.bmm(tensor1,tensor2) # (batch,n,p)
print(out_bmm)

tensor([[[5.0408, 3.9031, 4.3576,  ..., 3.0568, 4.7929, 3.2972],
         [5.4397, 4.6825, 5.2673,  ..., 4.2250, 6.7470, 4.9432],
         [5.7779, 5.2390, 6.1961,  ..., 4.2946, 6.6419, 4.6348],
         ...,
         [5.6094, 5.4529, 4.6194,  ..., 4.2911, 7.2305, 4.8028],
         [4.5664, 3.9362, 4.0528,  ..., 2.8152, 4.8406, 4.0744],
         [5.3715, 4.9994, 4.9218,  ..., 3.1238, 5.8491, 3.8810]],

        [[5.4019, 6.2067, 4.0780,  ..., 3.7039, 5.9432, 4.9837],
         [4.8032, 4.9164, 3.5576,  ..., 3.3919, 4.9504, 4.4352],
         [4.5536, 5.2467, 2.8115,  ..., 3.5215, 4.5710, 5.0998],
         ...,
         [5.0320, 5.1583, 3.5752,  ..., 3.9860, 5.5345, 4.1524],
         [5.5878, 4.9522, 3.5586,  ..., 3.6543, 5.0998, 5.1382],
         [6.9206, 6.4273, 5.2578,  ..., 4.3830, 6.3454, 6.4311]],

        [[5.5481, 5.7331, 5.8435,  ..., 6.2551, 6.0613, 5.8118],
         [4.6012, 4.6135, 5.4786,  ..., 5.5483, 4.5751, 4.7466],
         [5.3829, 5.4369, 6.3903,  ..., 5.8481, 5.2942, 5.

In [17]:
# 广播
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))
z = x1 - x2
print(z)
z = x1 ** x2
print(z)


tensor([[-0.0558, -0.6274,  0.1934, -0.2140, -0.3501],
        [-0.1267, -0.5197,  0.0428,  0.1047,  0.1921],
        [-0.0981,  0.1107,  0.4384,  0.4137, -0.1850],
        [ 0.0504,  0.2233,  0.7067,  0.5599, -0.2856],
        [-0.1940, -0.4505,  0.4669,  0.0871,  0.1908]])
tensor([[0.6567, 0.1309, 0.9627, 0.4446, 0.4903],
        [0.6004, 0.2859, 0.9349, 0.7701, 0.9382],
        [0.6239, 0.8509, 0.9809, 0.9025, 0.6390],
        [0.7312, 0.9314, 0.9922, 0.9493, 0.5502],
        [0.5400, 0.3659, 0.9824, 0.7603, 0.9373]])


In [30]:
# 一些有用的tensor操作
total = torch.sum(x) # 求和
# print(total) # tensor(6)
#最大值
val,index = torch.max(x,dim=0) # 也可以x.max(dim=0)
# print(val,index) # tensor(3) tensor(2)
#最小值
val,index = torch.min(x,dim=0) # 也可以x.min(dim=0)
# print(val,index) # tensor(1) tensor(0)
#绝对值
abs_val = torch.abs(x) # 注意:这个方法没有dim参数,也可以x.abs()
# print(abs_val)
# 获取最大的元素并且返回他的索引
mx_idx = torch.argmax(x) # 或者: mx_idx = torch.argmax(x,dim=0)也可以x.argmax(dim=0)
# print(mx_idx)
# 获取最小的元素并且返回他的索引
mn_idx = torch.argmin(x) # 或者: mx_idx = torch.argmin(x,dim=0)
# print(mn_idx)
# 均值
mean = torch.mean(x.float(),dim=0)
# print(mean)

# 判断两个tensor是否相等
ret = torch.eq(x,y)
# print(ret)
# 判断两个tensor是否不等
ret = torch.ne(x,y)
# print(ret)

#排序
sorted_y,indices = torch.sort(y,dim=0,descending=False) #升序排列
# print(sorted_y)
# print(indices)

#clamp(data,min=0) 如果data里面的元素小于这个min的值,就会把他们设置为min值,他也有一个max参数,如果data的元素大于这个max,就会强制把它设置为max
data = torch.tensor([-2,-1,0,2,4,5])
data2 = torch.clamp(data,min=0) # tensor([0, 0, 0, 2, 4, 5])
print(data2)
data = torch.tensor([-2,-1,0,2,4,5,7,8,9])
data2 = torch.clamp(data,min=0,max=7) # tensor([0, 0, 0, 2, 4, 5, 7, 7, 7])
print(data2)

# any()只要有一个元素符合条件,就会返回True
res = torch.any(data)
# print(res) # tensor(True)
# all()只有所有的元素符合条件,才返回True
res = torch.all(data)
print(res) # tensor(False)

tensor([0, 0, 0, 2, 4, 5])
tensor([0, 0, 0, 2, 4, 5, 7, 7, 7])
tensor(False)


In [38]:
# 索引操作
batch_size = 10
features = 25
t = torch.rand((batch_size,features))
# print(t[0].shape) # torch.Size([25])
# print(t[:,0].shape) # torch.Size([10])
# print(t[2,0:10]) # tensor([0.3433, 0.5274, 0.5691, 0.8528, 0.2644, 0.2485, 0.0693, 0.1275, 0.3163,0.5014]) 得到一个1行10列的tensor

t[0,0] = 10 #修改第一个元素的值
# print(t)

# 用索引选取你需要的元素
x = torch.arange(10)
# print(x)
indices = [2,5,8]
# print(x[indices]) # tensor([2, 5, 8])

# 可以指定行数和列数,这个有点复杂需要慢慢理解
x = torch.rand((3,5))
print(x)
rows = torch.tensor([1,0]) # 表示需要的行索引是1和0
cols = torch.tensor([4,0]) # 表示需要的列索引是4和0
# print(x[rows,cols]) # 根据位置的配对,获取元素x[1,4]和x[0,0]

# 条件索引
x = torch.arange(10)
print(x[(x<2)|(x>8)]) # tensor([0, 1, 9])


tensor([[0.8158, 0.5149, 0.2647, 0.4535, 0.1050],
        [0.3884, 0.1541, 0.5291, 0.4398, 0.9768],
        [0.3795, 0.9225, 0.3936, 0.8032, 0.8027]])
tensor([0, 1, 9])
